spring:
  application:    name: servicio-productos
  banner:    location: classpath:/message/banner.txt
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka