spring:
  application:    name: servicio-productos
#    Agregando Banner.
  banner:    location: classpath:/message/banner.txt
    
#    Configuración del puerto.
server:
  port: ${PORT:0}
  
#   Configuración de Eureka.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}