spring:
  application:    name: servicio-productos
  banner:    location: classpath:/message/banner.txt
    
#   Configuración para la Base de Datos.
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: m932006ac
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect    hibernate:      ddl-auto: create

#  Muestra en los logs los querys realizados en la base de datos.
logging:
  level:
    org: 
      hibernate:
        SQL: debug
    
#    Configuración del puerto.
server:
  port: ${PORT:0}
  
#   Configuración de Eureka.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}